.\" (c) copyright 2012 by Frank Nobis fn@radio-do.de
.Dd 11.10.2012			\" DATE
.Dt vcontrold 1
.Os Darwin
.Sh NAME
.Nm vcontrold
.Nd Unix daemon for Vito communication
.Sh SYNOPSIS
.Nm
.Op Fl x Ar xml-file
.Op Fl d Ar device
.Op Fl l Ar logfile
.Op Fl p Ar port
.Op Fl s
.Op Fl n
.Op Fl i
.Op Fl g
.Sh DESCRIPTION
.Nm
uses a serial link or an IP connection to communicate with a vito heating
system.
.Sh OPTIONS
The meaning of the different options is:
.Bl -hang -width -indent
.It Fl x
used to tell
.Nm vcontrold
where the main config file is found. See
.Xr FILES
for more info,
.It Fl d
specifies the serial device to use. This option overrides the device entry in the
.Ar xml
file.
.It Fl p
the TCP
.Ar port
to use for remote connections. The default is 3002 and can be specified in the
.Ar xml
file. This option overrides the corresponding option int the
.Ar xml
file.
.It Fl s
use syslog
.It Fl l
use
.Ar logfile
instead of syslog.
.It Fl n
do not fork. This is for testing purpose only. Normaly
.Nm vcontrold
will detach from the controlling terminal and put itself into the background.
.It Fl i
use a temp file in /tmp/sim-devid.ini for use with the vsim simulator
.It Fl g
enable debug mode.
.El
.Sh FILES
.Bl -tag -width "/etc/vcontrold/vcontrold.xml" -compact
.It Pa /etc/vcontrold/vcontrold.xml
These are the programm specific configurations. E.g. device, baudrate, IP etc.
.It Pa /etc/vcontrold/vito.xml
These are the command definitions for the devices in use.
.El                      \" Ends the list
.Sh SEE ALSO
.Xr vclient 1
.Sh AUTHORS
.An "Frank Nobis" Aq fn@radio-do.de
