name: Builds for RPi on RaspiOS
on:
  workflow_call:
    inputs:
      target:
        description: 'RPi base_image target'
        # see https://github.com/pguyot/arm-runner-action
        required: true
        default: 'raspios_lite:latest'
        type: string
        # type: choice
        # options:
        # - raspios_lite:latest
        # - raspios_lite_arm64:latest
        # - raspi_1_bullseye:20220121
      artifact_archive:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build on RaspiOs
      uses: pguyot/arm-runner-action@v2
      with:
        image_additional_mb: 1024
        base_image: ${{ inputs.target }}
        copy_artifact_path: build
        commands: |
            apt-get update -y --allow-releaseinfo-change
            apt-get install -y build-essential cmake libxml2-dev python3-docutils zip checkinstall
            mkdir build
            cmake -S . -B ./build  -DCMAKE_C_FLAGS="-Wall" -DCMAKE_VERBOSE_MAKEFILE=ON
            cmake --build ./build
            echo "ARCH=$(dpkg --print-architecture)" > ./build/env
    - name: Set env vars
      run: |
        cat ./build/env >> ${GITHUB_ENV}
        BUILD_DIR="${GITHUB_WORKSPACE}/build"
        echo "BUILD_DIR=${BUILD_DIR}" >> ${GITHUB_ENV}
        VERSION=$(sed -n -e 's/#define VERSION "\(.*\)"/\1/p' ${BUILD_DIR}/version.h)
        echo "VERSION=${VERSION}" >> ${GITHUB_ENV}
        GH_REPO=$(echo -n "${GITHUB_REPOSITORY}" | cut -d "/" -f 2)
        echo "GH_REPO=${GH_REPO}" >> ${GITHUB_ENV}
        echo DEPLOYFILEPREFIX="${GH_REPO}_${VERSION}" >> ${GITHUB_ENV}
        echo DEPLOYFILEPREFIX_BIN="${DEPLOYFILEPREFIX}-${GITHUB_RUN_NUMBER}_${ARCH}" >> ${GITHUB_ENV}
    - name: Collect files
      run: |
        BUILD_DIR=${GITHUB_WORKSPACE}/build
        cd ${BUILD_DIR}
        zip -j ${BUILD_DIR}/${DEPLOYFILEPREFIX_BIN}.zip ${BUILD_DIR}/build/vcontrold ${BUILD_DIR}/build/vclient ${BUILD_DIR}/build/doc/man/vcontrold.1.gz ${BUILD_DIR}/build/doc/man/vclient.1.gz ${BUILD_DIR}/COPYING ${BUILD_DIR}/README.md
        md5sum "${DEPLOYFILEPREFIX_BIN}.zip" > "${DEPLOYFILEPREFIX_BIN}.zip.md5sum"
        sha256sum "${DEPLOYFILEPREFIX_BIN}.zip" > "${DEPLOYFILEPREFIX_BIN}.zip.sha256sum"
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact_archive }}
        path: |
           build/*.zip
           build/*.zip.*sum
        if-no-files-found: error
            

